Add HTML form for eol_sso_login enroll/unenroll functionality within …
open-uchile/open-uchile-theme pull request #16
Opened 2024-05-22 13:52 UTC by tomaspemora

…the instructor tab

2024-05-22 16:50 UTC, fsologureng requested changes
Hay algunas cosas que no entiendo al final del código html que no comenté, pero lo demás me parece que necesita algún grado de reestructuración para hacer el código más usable y accesible.

2024-05-22 16:50 UTC, fsologureng commented on lms/templates/instructor/instructor_dashboard_2/membership.html
> +    ${_("Ingrese el RUT o Pasaporte de lo usuarios que desea inscribir. Si es más de uno, utilice saltos de lineas para diferenciar cada usuario.")}</br>
Si bien las instrucciones para el llenado del campo son necesarias, el elemento `label` no es para la descripción del campo, si no sólo para su nombre. Habrá otra forma de ingresar las instrucciones en algún párrafo o similar que tenga un estilo acorde, pero complementario al nombre del campo?

Por otro lado, aunque vinculado con lo anterior, en su forma anidada el label no debe tener hijos que no sean campos del form, y por defecto se asigna al 1er elemento hijo cuandohubiese más; por tanto no se está asignando bien el `label` al `textarea` si no al primer `br`.

2024-05-22 16:50 UTC, fsologureng commented on lms/templates/instructor/instructor_dashboard_2/membership.html
> +      ${_("Enter email addresses and/or usernames separated by new lines or commas.")}
Mismo tema con el label del textarea anterior.

2024-05-22 16:50 UTC, fsologureng commented on lms/templates/instructor/instructor_dashboard_2/membership.html
> +          ${_("Enter the reason why the students are to be manually enrolled or unenrolled.")}
Ídem anteriores.

2024-05-22 16:50 UTC, fsologureng commented on lms/templates/instructor/instructor_dashboard_2/membership.html
> +          <span class="label-text">${_("Auto Enroll")}</span>
Ídem labels anteriores.

2024-05-22 16:50 UTC, fsologureng commented on lms/templates/instructor/instructor_dashboard_2/membership.html
> +          <div class="hint auto-enroll-hint">
`div` no puede ser hijo de `span`. Cambiar el `span` por otro `div`.

2024-05-22 16:50 UTC, fsologureng commented on lms/templates/instructor/instructor_dashboard_2/membership.html
> +                  <br /><br />
Podría probarse agregar otro párrafo en vez de los br. Debiera ser equivalente.

2024-05-22 16:50 UTC, fsologureng commented on lms/templates/instructor/instructor_dashboard_2/membership.html
> +      <label class="has-hint">
Ídem anteriores.

2024-05-22 16:50 UTC, fsologureng commented on lms/templates/instructor/instructor_dashboard_2/membership.html
> +        <input type="checkbox" name="email-students" id="email-students" value="Notify-students-by-email" aria-describedby="heading-batch-enrollment"
El atributo `aria-describedby` no puede apuntar a un elemento cuyo objetivo descriptivo es de otro elemento (`legend`). Debe apuntar a un descriptor dedicado o cambiarse por `aria-description` con su descripción in situ.

2024-05-22 16:50 UTC, fsologureng commented on lms/templates/instructor/instructor_dashboard_2/membership.html
> +  <p>${_("To register and enroll a list of users in this course, choose a CSV file that contains the following columns in this exact order: email, username, name, and country. Please include one stud
Esta diagramación de las instrucciones (en párrafo `p`) es la apropiada en vez del uso de los labels de los campos.

2024-05-22 16:50 UTC, fsologureng commented on lms/templates/instructor/instructor_dashboard_2/membership.html
> +      <span id="browseFile" class="enhanced-input-file"></span>
Este texto para ser mejor como legend del form.

2024-05-22 16:50 UTC, fsologureng commented on lms/templates/instructor/instructor_dashboard_2/membership.html
> +  <label>
Ídem `label` anteriores.

2024-05-22 16:50 UTC, fsologureng commented on lms/templates/instructor/instructor_dashboard_2/membership.html
> +      <label class="has-hint">
Ídem

2024-05-22 16:50 UTC, fsologureng commented on lms/templates/instructor/instructor_dashboard_2/membership.html
> +## Translators: an "Administration List" is a list, such as Course Staff, that users can be added to.
Qué es esto? Si es un comentario al código, tengo la impresión de que esto se ve en el html.

2025-10-02 17:27 UTC, tomaspemora commented
Desechado. Podría abordarse en eol_sso_login pero por ahora no es prioridad.

2025-10-02 17:27 UTC, closed without merging