feat: modify login to give to options
open-uchile/open-uchile-theme pull request #23
Opened 2024-08-23 20:20 UTC by catalinaIlabaca

Se agregaron dos botones que representan las opciones de ingreso, mi uchile o el propio open, además se corrieron las traducciones nuevamente

2024-08-23 21:21 UTC, fsologureng requested changes

2024-08-23 21:21 UTC, fsologureng commented on lms/templates/student_account/login.underscore
> +                            <div class="icon <% if ( provider.iconClass ) { %>fa <%- provider.iconClass %><% } %>" aria-hidden="true">
Este contenedor debería ser un `span` porque está dentro de un `button`.

2024-08-23 21:21 UTC, fsologureng commented on lms/templates/student_account/login.underscore
> +    function loginCorreo() {
Esto es necesario? entiendo que estamos sacando el login via correo...

2024-08-23 21:21 UTC, fsologureng commented on lms/templates/student_account/login.underscore
> +        if(window.location.href.includes("cuenta_eol")){
Qué es esto?

2024-08-23 21:21 UTC, fsologureng commented on lms/templates/student_account/login.underscore
> +        var url = document.getElementById("url_next").textContent;
Al parecer estas 4 lineas están repetidas y de sobra...

2024-08-23 21:21 UTC, fsologureng commented on lms/templates/student_account/login_and_register.html
>      $('#login-email').live('keydown', function(e) {
este evento sirve para deshabilitar el Enter cuando se ha completado el email. Para qué queremos eso?

2024-08-23 21:21 UTC, fsologureng commented on lms/templates/student_account/login_and_register.html
> +    $('#redirect_to').live('click', function(e){
por qué cambiaste el id? me parece que estaba bien el anterior. Es más semántico que un redirect en general (aunque el sso haga un redirect).

2024-08-23 21:21 UTC, fsologureng commented on lms/templates/student_account/register.underscore
Habíamos quedado que borrar este template implicaría que el tema open-uchile-theme pasaría a tener el estilo vanilla del edx para el form de registro. Me parece que tenemos que conservar el estilo del tema.
Tú habías esgrimido que el form de registro está en otro path y por ende usa otra plantilla, pero no me queda claro que así sea. De lo contrario edx no mantendría esta plantilla en la base.

Por último, si no se usara esta plantilla, entonces tiene que ser también eliminada del loop que carga las templates underscore como templates html en la página.

2024-08-27 13:20 UTC, fsologureng requested changes

2024-08-27 13:20 UTC, fsologureng commented on lms/templates/student_account/login.underscore
> +        <button id="sso_btn" class=" action-primary w-100" style="margin-bottom:1.5rem">Iniciar Sesión con Mi.UChile</button>
Este sigue pendiente

2024-08-27 15:45 UTC, fsologureng reviewed
Remover lineas en blanco, pero no es imprescindible ahora. Queda pendiente para terminar el PR después del feedback de EOL.

2024-08-27 15:45 UTC, fsologureng commented on lms/templates/student_account/login.underscore
> +
Linea sobrante. Remover.

2024-08-27 15:45 UTC, fsologureng commented on lms/templates/student_account/login.underscore
> +
Linea sobrante. Remover

2024-08-27 15:45 UTC, fsologureng commented on lms/templates/student_account/login.underscore
> +
Linea sobrante. Remover.

2024-08-27 15:45 UTC, fsologureng commented on lms/templates/student_account/login.underscore
> +
Linea sobrante. Remover.

2024-08-27 15:45 UTC, fsologureng commented on lms/templates/student_account/login.underscore
> +
Linea sobrante. Remover.

2024-08-27 17:06 UTC, fsologureng approved these changes

2024-08-27 18:07 UTC, tomaspemora approved these changes

2024-08-29 21:10 UTC, fsologureng commented
@catalinaIlabaca el último commit no puede ser `feat` y al mismo tiempo `fix`. Hacer ammend del mensaje a `fix:`

2024-09-11 03:53 UTC, tomaspemora commented
style: update login form layout for better responsiveness
```diff
diff --git a/lms/templates/student_account/login.underscore b/lms/templates/student_account/login.underscore
index 06bcf19..00366f9 100755
--- a/lms/templates/student_account/login.underscore
+++ b/lms/templates/student_account/login.underscore
@@ -19,34 +19,53 @@
 <form id="login" class="login-form" tabindex="-1" method="POST">
 
     <div id="js-form-feedback" class="js-form-feedback" aria-live="assertive" tabindex="-1"></div>
-        <div id="pre_login"> 
-          <div class="col-11">
-            <button id="href_login_normal" type="button" class="font-size-16 w-100 dark-blue-button p-2 font-weight-bold" href="#Login_Normal" onclick="return show_email_login();"><span class="font-weight-normal"><%- gettext("Log in with your account")%></span> OpenUChile</button>
-               </div>
+        <div id="pre_login">
             <div class="row">
-          
-                <div class="col-11">
-                    
-                    <img class="uchile-separator img-login" src="/static/open-uchile-theme/images/uchile_separator.png" alt="">
-                    <button id="sso_btn" type="button" class=" font-size-16 w-100 login-open-u-chile-button font-weight-bold" ><span class="font-weight-normal"><%- gettext("Log in with your account")%></span>  Mi.UChile</button>
-                </div>
-                <div class="col-1 mt-2 text-center align-items-center d-flex">
-                    <i id="info-miUchile" class="fa fa-info-circle" aria-hidden="true" data-bs-toggle="tooltip" data-bs-placement="top" title="Información adicional"></i>
+                <div class="col-12">
+                    <div class="row">
+                        <div class="col-1 mt-2 d-flex"></div>
+                        <div class="col-10">
+                            <button id="href_login_normal" type="button" class="font-size-16 w-100 dark-blue-button p-2 font-weight-bold" href="#Login_Normal" onclick="return show_email_login();"><span class="font-weight-normal"><%- gettext("Log in with your account")%></span> OpenUChile</button>
+                        </div>
+                        <div class="col-1 mt-2 d-flex"></div>
+                    </div>
+                    <div class="row">
+                        <div class="col-1 mt-2 d-flex"></div>
+                        <div class="col-10">
+                            <img class="uchile-separator img-login" src="/static/open-uchile-theme/images/uchile_separator.png" alt="">
+                            <button id="sso_btn" type="button" class=" font-size-16 w-100 login-open-u-chile-button font-weight-bold" ><span class="font-weight-normal"><%- gettext("Log in with your account")%></span>  Mi.UChile</button>
+                        </div>
+                        <div class="col-1 mt-2 px-0 px-sm-2 text-left align-items-center d-flex">
+                            <i id="info-miUchile" class="fa fa-info-circle w-100" aria-hidden="true" data-bs-toggle="tooltip" data-bs-placement="top" title="Información adicional"></i>
+                        </div>
+                    </div>
                 </div>
+
             </div>
-            <div id="login_separator" class="separator col-11"><%- gettext("Or") %></div>
-            <div id="register-div" class="col-11">
-                <h1><%- gettext("Don't have an account?") %></h1>
-                <div class=" justify-content-center">
-                    <button id="register_btn" type="button" class="font-size-16 font-weight-bold w-100 register-button-color"><%- gettext("Create account") %></button>
-                </div>
+            <div class="row">
+                <div id="login_separator" class="separator col-12"><%- gettext("Or") %></div>
+            </div>
+
+
+            <div class="row">
+                <div class="col-1 mt-2 d-flex"></div>
+                <div id="register-div" class="col-10">
+                    <div class="row">
+                        <h1><%- gettext("Don't have an account?") %></h1>
+                    </div>
+                    <div class="row">
+                        <div class=" justify-content-center">
+                            <button id="register_btn" type="button" class="font-size-16 font-weight-bold w-100 register-button-color"><%- gettext("Create account") %></button>
+                        </div>
+                    </div>
+                </div> 
+                <div class="col-1 mt-2 d-flex"></div>
             </div>
         </div>
     </div>
-     
     <div id="Login_Normal" class="login-providers d-none text-start">
         <div class="row">
-            <div class="col-2 mt-2 text-center">
+            <div class="col-2 mt-2 text-center user-select-none">
                 <i id="go-back-icon" class="fa fa-arrow-circle-o-left fa-2x" aria-hidden="true"></i>
                 <p><%- gettext("Go back")%></p>
             </div>
@@ -127,6 +146,7 @@
     };
     function show_email_login() {
         $('#Login_Normal').removeClass('d-none');
+        $('#login-subtitle').removeClass('d-none');
         $('#pre_login').hide();
         $('#js-form-feedback').find('*').remove();
         changeFontSiZe();
@@ -134,6 +154,7 @@
     };
     function show_pre_login() {
         $('#Login_Normal').addClass('d-none');
+        $('#login-subtitle').addClass('d-none');
         $('#pre_login').show();
         $('#login-email').val('');
         $('#login-password').val('');
diff --git a/lms/templates/student_account/login_and_register.html b/lms/templates/student_account/login_and_register.html
index 4593ea4..2b084e8 100755
--- a/lms/templates/student_account/login_and_register.html
+++ b/lms/templates/student_account/login_and_register.html
@@ -39,8 +39,8 @@
     % endfor
 </%block>
 <div class="visually-hidden" id="url_next">${ reverse('eol_sso_login:uchile_login') | h }?${urlencode({'next':login_redirect_url})}</div>
-<div class="container px-3 mt-2">
-    <div class="card col-11 col-md-8 col-lg-7 mx-auto shadow-lg px-5 py-4 mb-5 rounded-lg" id="content-container">
+<div class="container px-1 px-md-3 mt-2">
+    <div class="card col-12 col-md-8 col-lg-7 mx-auto shadow-lg px-0 px-md-5 py-4 mb-5 rounded-lg" id="content-container">
         % if enable_enterprise_sidebar:
             <%include file="enterprise_sidebar.html" />
             <%

```

2024-09-13 00:42 UTC, tomaspemora commented
@catalinaIlabaca @fsologureng Agregué todos los cambios mencionados en la reunion de hoy. Lo único que no me convence es la posición del botón volver en el login.
![image](https://github.com/user-attachments/assets/e819f854-faae-4f9a-8136-0158932541dc)

le apliqué la técnica de col-1 col-10 col-1 al form de register también.

2024-09-13 12:46 UTC, fsologureng commented
>  Lo único que no me convence es la posición del botón volver en el login.

Sugiero preguntarle a Consu.

2024-09-13 16:35 UTC, tomaspemora approved these changes

2024-09-13 16:36 UTC, merged